import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
let db,groupId,issueId,invite,questions;
const owner='11111111-1111-4111-8111-111111111111',mate='22222222-2222-4222-8222-222222222222',outsider='33333333-3333-4333-8333-333333333333';
async function as(id,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:id,email:(id===owner?'owner':id===mate?'mate':'outsider')+'@example.com',role})]);await db.exec('set role '+role)}
async function rpc(action,payload={},g=groupId){return (await db.query('select public.ll_mutate($1,$2,$3::jsonb) data',[action,g,JSON.stringify(payload)])).rows[0].data}
async function state(){return (await db.query('select public.ll_state() data')).rows[0].data}
before(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;create function auth.uid() returns uuid language sql stable as $$select (auth.jwt()->>'sub')::uuid$$;grant usage on schema auth to authenticated,service_role;grant execute on all functions in schema auth to authenticated,service_role;insert into auth.users values('${owner}'),('${mate}'),('${outsider}');`);for(const f of ['202610070001_core.sql','202610070002_jobs.sql'])await db.exec(await readFile('supabase/migrations/'+f,'utf8'))});
after(async()=>db?.close());
test('owner creates a real group and invite; no seed users exist',async()=>{await as(owner);const r=await rpc('create',{name:'Friends',description:'Our stories',cadence:14,timezone:'Europe/Brussels'},null);groupId=r.groupId;const s=await state();assert.equal(s.groups.length,1);assert.equal(s.groups[0].members.length,1);issueId=s.groups[0].issue.id;questions=s.groups[0].issue.questions;invite=(await rpc('invite')).token;assert.equal(invite.length,64)});
test('anonymous and outsiders cannot read or alter group data',async()=>{await as(outsider);assert.equal((await state()).groups.length,0);await assert.rejects(rpc('settings',{name:'Hijacked'}),/access/);await assert.rejects(db.query('select * from private.replies'),/permission/);await as(null,'anon');await assert.rejects(state(),/permission/);await assert.rejects(db.query('select public.ll_tick()'),/permission/)});
test('invited mate joins once and can ask a question without owner privileges',async()=>{await as(mate);await rpc('join',{token:invite},null);await rpc('join',{token:invite},null);assert.equal((await state()).groups[0].members.length,2);await rpc('suggest',{text:'What would you love to do together?'});assert.equal((await state()).groups[0].suggestions.length,1);await assert.rejects(rpc('invite'),/owner/);await assert.rejects(rpc('compile',{issueId}),/owner/)});
test('drafts remain private; questions lock when a reply starts',async()=>{await as(owner);await rpc('reply',{issueId,answers:{[questions[0].id]:'My private first draft'},submitted:false,revision:0});await as(mate);const issue=(await state()).groups[0].issue;assert.equal(Object.keys(issue.responses).length,0);assert.equal(issue.questionsLocked,true);await as(owner);assert.equal((await state()).groups[0].issue.responses[owner].submitted,false);await assert.rejects(rpc('questions',{issueId,questions:[{text:'Changed question'}]}),/locked/)});
test('complete submitted answers become visible to other members; stale writes are rejected',async()=>{await as(owner);await assert.rejects(rpc('reply',{issueId,answers:{},submitted:true,revision:1}),/each question/);const answers=Object.fromEntries(questions.map((q,i)=>[q.id,'Owner story '+i]));await rpc('reply',{issueId,answers,submitted:true,revision:1});await assert.rejects(rpc('reply',{issueId,answers,submitted:false,revision:1}),/another tab/);await as(mate);const s=await state();assert.equal(s.groups[0].issue.responses[owner].answers[questions[0].id],'Owner story 0');await rpc('reaction',{questionId:questions[0].id,authorId:owner,liked:true});assert.equal((await state()).groups[0].issue.likes[questions[0].id+'-'+owner].count,1)});
test('manual compilation archives answers and uses member suggestions for the next round',async()=>{await as(owner);await rpc('compile',{issueId});const s=await state();assert.equal(s.groups[0].archive.length,1);assert.equal(s.groups[0].issue.number,2);assert.equal(s.groups[0].issue.questions[0].text,'What would you love to do together?');assert.equal(s.groups[0].suggestions.length,0);await assert.rejects(rpc('reply',{issueId,answers:{},submitted:true,revision:2}),/closed/)});
test('scheduler is service-only, queue claims are leased and sent jobs never reappear',async()=>{await as(mate);await assert.rejects(db.query('select public.ll_claim_email()'),/permission/);await as(null,'service_role');await db.query('select public.ll_tick()');const jobs=(await db.query('select public.ll_claim_email() data')).rows[0].data;assert.ok(jobs.length>=2);const again=(await db.query('select public.ll_claim_email() data')).rows[0].data;assert.equal(again.length,0);for(const job of jobs)assert.equal((await db.query('select public.ll_finish_email($1,$2,$3) done',[job.id,job.leaseToken,'provider-id'])).rows[0].done,true);assert.equal((await db.query('select public.ll_claim_email() data')).rows[0].data.length,0)});
test('turning off email updates cancels queued mail; removed members lose access',async()=>{await as(owner);const s=await state();const next=s.groups[0].issue;await db.exec('reset role');await db.query("update private.issues set due_at=now()+interval '24 hours' where id=$1",[next.id]);await as(null,'service_role');await db.query('select public.ll_tick()');await as(mate);await rpc('notifications',{enabled:false});await as(null,'service_role');const jobs=(await db.query('select public.ll_claim_email() data')).rows[0].data;assert.ok(jobs.every(j=>j.email!=='mate@example.com'));await as(owner);await rpc('remove-member',{id:mate});await as(mate);assert.equal((await state()).groups.length,0);await assert.rejects(rpc('suggest',{text:'Not a member'}),/access/)});
test('revoked invites cannot be used, and owner cannot remove self',async()=>{await as(owner);await rpc('revoke-invites');await assert.rejects(rpc('remove-member',{id:owner}),/owner/);await as(outsider);await assert.rejects(rpc('join',{token:invite},null),/expired/)});

test('paused groups defer queued email, resume preserves it, and due issues close once',async()=>{
 await as(owner);let g=(await state()).groups[0];const payload={name:g.name,description:g.description,cadence:g.cadence,timezone:g.timezone,paused:true};
 await rpc('settings',payload);await db.exec('reset role');await db.query("update private.issues set due_at=now()-interval '1 minute' where id=$1",[g.issue.id]);
 await as(null,'service_role');assert.equal((await db.query('select public.ll_tick() data')).rows[0].data.closed,0);assert.equal((await db.query('select public.ll_claim_email() data')).rows[0].data.length,0);
 await as(owner);await rpc('settings',{...payload,paused:false});await as(null,'service_role');assert.equal((await db.query('select public.ll_tick() data')).rows[0].data.closed,1);assert.equal((await db.query('select public.ll_tick() data')).rows[0].data.closed,0);
 const jobs=(await db.query('select public.ll_claim_email() data')).rows[0].data;assert.ok(jobs.length>0);for(const j of jobs){assert.equal((await db.query('select public.ll_finish_email($1,$2,$3) done',[j.id,outsider,'wrong lease'])).rows[0].done,false);await db.query('select public.ll_finish_email($1,$2,$3)',[j.id,j.leaseToken,'provider-ok']);}
 await as(owner);g=(await state()).groups[0];assert.equal(g.archive.length,2);assert.equal(g.issue.number,3);assert.ok(Date.parse(g.issue.due_at)>Date.now());
});
