import {test} from 'node:test';
import assert from 'node:assert/strict';
const env=new Map(Object.entries({JOB_SECRET:'test-job-secret',SUPABASE_URL:'https://test.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test-service-key',BREVO_API_KEY:'test-provider-key',BREVO_SENDER_EMAIL:'sender@example.com',APP_URL:'https://example.com/friends/'}));
let handler;
globalThis.Deno={env:{get:n=>env.get(n)},serve:fn=>{handler=fn}};
await import('../supabase/functions/reminders/index.ts');
const request=secret=>new Request('https://test.supabase.co/functions/v1/reminders',{method:'POST',headers:{'x-job-secret':secret}});
const jobs=[{id:'job-1',leaseToken:'lease-1',kind:'reminder',groupId:'group-1',groupName:'Friends <script>',issueId:'issue-1',email:'friend@example.com',name:'A mate',deadline:'Tomorrow'}];
let calls=[];
function mock(providerStatus=201){calls=[];globalThis.fetch=async(url,options)=>{const body=JSON.parse(options.body);calls.push({url,body,headers:options.headers});if(url.endsWith('/ll_tick'))return Response.json({closed:0});if(url.endsWith('/ll_claim_email'))return Response.json(jobs);if(url.endsWith('/ll_finish_email'))return Response.json(true);if(url==='https://api.brevo.com/v3/smtp/email')return Response.json({messageId:'provider-1'},{status:providerStatus});throw Error('Unexpected network call')};}
test('reminder endpoint refuses unauthorised calls before touching services',async()=>{mock();assert.equal((await handler(request('wrong-secret'))).status,401);assert.equal(calls.length,0);assert.equal((await handler(new Request('https://example.com/'))).status,405)});
test('authenticated dispatch escapes group text and acknowledges the leased job',async()=>{mock();const response=await handler(request('test-job-secret'));assert.equal(response.status,200);assert.equal((await response.json()).sent,1);const email=calls.find(c=>c.url.includes('brevo.com')).body;assert.equal(email.to[0].email,'friend@example.com');assert.ok(email.htmlContent.includes('&lt;script&gt;'));assert.ok(!email.htmlContent.includes('<script>'));assert.ok(email.htmlContent.includes('group=group-1'));assert.equal(email.headers.idempotencyKey,'job-1');const finish=calls.find(c=>c.url.endsWith('/ll_finish_email'));assert.equal(finish.body.p_lease,'lease-1');assert.equal(finish.body.p_provider_id,'provider-1');assert.equal(finish.body.p_error,undefined)});
test('provider failure is recorded without declaring email sent',async()=>{mock(429);const response=await handler(request('test-job-secret'));assert.equal(response.status,503);const result=await response.json();assert.equal(result.sent,0);assert.equal(result.failed,1);const finish=calls.find(c=>c.url.endsWith('/ll_finish_email'));assert.match(finish.body.p_error,/429/);assert.equal(finish.body.p_provider_id,undefined)});
